import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomTitleBar from "./components/wrappers/controller";
import SideBar from "./components/wrappers/sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppAPIProvider } from "@/contexts/AppAPI";
import { ThemeProvider } from "next-themes";
import { ProfileApiProvider } from "@/contexts/ProfileContext";
import { ExtensionsApiProvider } from "@/contexts/ExtensionManagerContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-y-hidden`}
      >
        <ThemeProvider defaultTheme="dark">
          <AppAPIProvider>
            <ProfileApiProvider>
              <ExtensionsApiProvider>
                <SidebarProvider defaultOpen={false}>
                  <div className="flex flex-col w-full relative">
                    <CustomTitleBar />
                    <main>
                      <SideBar />
                      {children}
                    </main>
                  </div>
                </SidebarProvider>
              </ExtensionsApiProvider>
            </ProfileApiProvider>
          </AppAPIProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
